name: GeniCan
favicon: null
layout_spectrum: 0.27247
typography_spectrum: 0.16892
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#555655'
    - '#009ed5'
    - '#89b63f'
    - '#ffffff'
    - '#181717'
  brandStrength: 0.5831423480994999
  lightness: 0.5770290847867727
  saturation: 0.1654001066926867
  rhythmicContrast: 0.3326280082110316
purpose: []
